baseURL = 'https://localhost:1313/'
languageCode = 'en-us'
defaultContentLanguage = "en"
theme = 'anubis2'
title = '金石台'

# buildFuture = true
timezone = "Asia/Shanghai"
# rssIcon = false # true | false; Showing RSS icon; default: true

[author]
name = "Jin Shi Tai"
email  = "shawnfinelee@163.com"
location = "Beijing"

[menu]
[[menu.main]]
name = "Home"
pageRef = "/"
weight = 1

# [[menu.main]]
# name = "Posts"
# url = "/posts/"
# weight = 2

[[menu.main]]
name = "About"
url = "/about/"
weight = 3

# [languages]
# [languages.zh]
# languageName = "Chinese"

# [[languages.zh.menu.main]]
# identifier = "archive"
# name = "归档"
# url = "/posts/"
# weight = 4

[params]
# readMore = false # true | false; Showing readmore link in the list of posts; default: false
# readNextPosts = 3 # Number of posts to show in the "Read Next" section; default: 3
colorTheme = "auto" # "auto" | "light" | "dark"; default: "auto"
colorThemeSwitcher = true # true | false; Showing color theme switcher in top of the site; default: false
toc = true # true | false; Showing table of contents in the post; default: true
# math = false # true | false; Enable MathJax; default: false; You can enable MathJax in the post by adding math: true in a post's metadata section.

# check more social icons at https://github.com/Junyi-99/hugo-theme-anubis2/wiki/Social-Icons
# social = [
    # { id="github", name="Junyi-99" },
    # { id="linkedin", url="https://www.linkedin.com/in/junyi-99/" },
    # { id="email", name="shawnfinelee@163.com" },
# ]

# icp = "京ICP备xxxxx号-1"

[taxonomies]
tag = "tags" # This allows you to use the "tags" in your markdown metadata

[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style
