baseURL = 'https://shawnfinelee.github.io/'
publishDir = "docs"


[params]
GiscusRepo = "shawnfinelee/shawnfinelee.github.io"
GiscusRepoId = "R_kgDOMJJIQg"
GiscusCategory = "Announcements"
GiscusCategoryId = "DIC_kwDOMJJIQs4CgHdl"
GiscusLazyLoad = true
GiscusDataMapping = "pathname"
GiscusLang = "zh-CN"


[params.UmamiAnalytics]
enabled = true
dnt = false
id = "7f48681e-9299-4262-a207-e4e4464482d7"
datacache = true
url = "https://cloud.umami.is/script.js"
shareUrl = "https://cloud.umami.is/share/4pgWfJSJsLh7xyu0/8crane.co.in"
